TRUTH = (
    "Pernah nge ghosting?" "pernah coli/colmek?",
    "ukuran bra kamu?" "ukuran tytyd kamu?",
    "berapa kali coli/colmek seminggu?",
    "pap nenen keliatan muka atau pap full naked tanpa muka?",
    "hal yang paling kamu takutin?" "fantasy ternakal kamu?",
    "threesome atau berdua aja" "gangbang atau bdsm?",
    "first kiss saat usia?" "pernah sange ketemen sekelas?",
    "pernah selingkuh?" "daerah sensitif lu?",
    "kapan lo lepas perkaja/perawan?",
    "pernah hs?" "hal paling liar (sex) yang lo lakuin",
    "kapan coli/colmek pertama lu?" "terakhir HS sama siapa?",
    "sejak umur berapa lo nonton bokep?" "kontol/memek lo berjembut",
    "suka romance/bdsm/hardsex?" "cowok/cewek gmna yang bisa bikin lo sange?",
    "minder gak sama ukuran kontol/toket lo?" "warna bh/tanktop yang lo pake skrang?",
    "warna celana dalam yang lo pake sekarang?" "pakaian tidur lo kaya apa?",
    "ceritakan pengalaman pertama toket/kontol lo disentuh lawan jenis?" "Genre bokep favorite?",
)

DARE = (
    "pm open vcs dan ss klo ada yang chat lo"
    "ajakin 1 temen lu fcs di rc terus ss",
    "pap muka lo",
    "send pap memalukan lo",
    "gombalin 1 temen lu di rc terus ss",
    "ajakin salah satu temen lo ngeroom",
    "minta lah pap tytyd ke temen/pacar/fams lo terus SS",
    "SS bekas play lo",
    "spill pinned chat lo",
    "spill galery lo",
    "spill ch bokep lo",
    "cubit pentil lo",
    "spill crush lo",
    "send pap naked lo ke salah satu rc lo",
    "send pap bh lo",
    "tease 1 cewek/cowok di rc lo lalu ss",
    "pap celana dalam lo",
    "spill kapan terakhir kali cukur jembot",
    "pap muka bangun tidur lo",
    "spill fetish lo",
    "ceritain pengalaman firs time coli/colmek lo",
    "spill hal yang bikin lo auto sange",
    "send sticker nakal ke cowok yang ada di rc lo lalu SS",
    "spill vid terakhir yang lo buat",
    "ajak jadian seseorang abis itu putusin tanpa bilang ini dare",
    "godain cewek/cowok orang lalu ss",
    "tease cewe/cowok orang lalu ss",
    "send ss an galery lo",
    "send history browser lo",
    "spill history call telegram lu",
    "spill history call whatsapp lu",
    "ajakin temen/fams lu fwb an!",
    "chat 1 ddk/mmk terus ajak mereka play",
    "ajak fc ddk/mmk",
    "ajak vc ddk/mmk",
    "spill selfie terjelek lo",
    "send selfie tergaring lo",
    "nyatain perasaan lo ke crush lo",
    "ajakin salah satu fams lo jadian",
    "bikin kesel salah satu fams lo",
    "send pm klo lo sange",
    "send pm klo lo mau berbagi pap toket/kontol",
    "send pm bebas sih yah",
    "dalah anjing segitu aja gua capek -arka",
    "coba beri gua ide buat truth and dare lainnya -arka",
    "bilang klo arka ganteng",
    "arka itu manis kan",
    "isi secreto arka yak kak!",
    "dah keabisan ide buat dare",
    "berikan saya dare apa lagi memek!",
)
